##############################################################################
# IA32_GNU:		Intel Pentium with Linux using GNU compiler gfortran.
##############################################################################
F90_SER = gfortran
F90_OMP = 
F90_MPI = mpif90
FLAGS_OPT = -O
FLAGS_MSC = -w
FLAGS_F90 =
FLAGS_SER =
FLAGS_OMP =
FLAGS_MPI =
INCS_SER =
INCS_OMP =
INCS_MPI =
LIBS_SER =
LIBS_OMP =
LIBS_MPI =
OUT = -o 
EXTO = o
MAKE = make
RM = rm -f
swch = -unix -f95 -timg
