# Compiler Paths
set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)
set(CMAKE_Fortran_COMPILER gfortran)

# Compiler Flags
set(CMAKE_C_FLAGS_RELEASE "-DNDEBUG -O3")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-DNDEBUG -g -O2")
set(CMAKE_C_FLAGS_DEBUG "-O0 -g")

set(CMAKE_CXX_FLAGS_RELEASE "-DNDEBUG -O3")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-DNDEBUG -g -O2")
set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g")

set(CMAKE_Fortran_FLAGS_RELEASE "-O3")
set(CMAKE_Fortran_FLAGS_RELWITHDEBINFO "-O3 -g")
set(CMAKE_Fortran_FLAGS_DEBUG "-O0 -g")

# Library Paths
set(ENABLE_OUTPUT_NETCDF ON)
# SET(NETCDFHOME /path/to/netcdf-root) SET(NETCDF_F90_ROOT /path/to/netcdf-fortran-root)

# Adjust default behaviors
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
