# CMake Toolchain file for the Docker container used on CircleCI
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)

# Set the build type (Release, Debug, RelWithDebInfo, MinSizeRel)
SET(CMAKE_BUILD_TYPE Release)

# Compiler Paths
SET(CMAKE_C_COMPILER gcc)
SET(CMAKE_CXX_COMPILER g++)
SET(CMAKE_Fortran_COMPILER gfortran)
SET(MPI_C_COMPILER mpicc)
SET(MPI_CXX_COMPILER mpicxx)
SET(MPI_Fortran_COMPILER mpif90)

# Executables
SET(ADCIRC_BUILD_ADCIRC ON)
SET(ADCIRC_BUILD_PADCIRC ON)
SET(ADCIRC_BUILD_ADCSWAN ON)
SET(ADCIRC_BUILD_PADCSWAN ON)
SET(ADCIRC_BUILD_ADCPREP ON)
SET(ADCIRC_BUILD_UTILITIES ON)
SET(ADCIRC_BUILD_ASWIP ON)
SET(ADCIRC_BUILD_SWAN ON)
SET(ADCIRC_BUILD_PUNSWAN ON)
SET(ADCIRC_BUILD_LIBADCIRC_STATIC ON)
SET(ADCIRC_BUILD_LIBADCIRC_SHARED ON)

# Strict compiler flags
SET(ADCIRC_STRICT_COMPILE ON)

# Adjust default behaviors
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)