#!/usr/bin/env python3

"""
Code to source the ADCIRC version from the git commit hash and tag
and optionally create a version file for use within the code
"""

from typing import Tuple


class AdcircVersion:
    def __init__(self, directory: str):
        """
        Initialize the ADCIRC version object

        Args:
            directory (str): The directory to create the version file in or the directory to search for the version file
        """
        self.__directory = directory
        version_dict = AdcircVersion.__query_adcirc_version(self.__directory)
        self.__tag = version_dict["tag"]
        self.__hash = version_dict["hash"]
        self.__version_major = version_dict["version_major"]
        self.__version_minor = version_dict["version_minor"]
        self.__version_patch = version_dict["version_rev"]

    def tag(self) -> str:
        """
        Get the ADCIRC version tag

        Returns:
            str: The ADCIRC version tag
        """
        return self.__tag

    def hash(self) -> str:
        """
        Get the ADCIRC version hash

        Returns:
            str: The ADCIRC version hash
        """
        return self.__hash

    @staticmethod
    def __query_adcirc_version(directory: str) -> dict:
        """
        Code to source the ADCIRC version from the git commit hash and tag

        Args:
            directory (str): The directory to create the version file in or the directory to search for the version file

        Returns:
            None
        """
        import os

        git_hash = "unknown"
        git_tag = "unknown"
        version_major = 0
        version_minor = 0
        version_patch = 0

        if AdcircVersion.__in_git_repo():
            git_hash, git_tag = AdcircVersion.__get_git_hash()
            try:
                version_major, version_minor, version_patch = (
                    AdcircVersion.__get_version_from_tag(git_tag)
                )
            except ValueError:
                pass
        elif os.path.exists(os.path.join(directory, "version.F90")):
            filename = os.path.join(directory, "version.F90")
            git_hash, git_tag, version_major, version_minor, version_patch = (
                AdcircVersion.__parse_version_file(filename)
            )
        else:
            raise RuntimeError("Could not determine ADCIRC version")

        return {
            "tag": git_tag,
            "hash": git_hash,
            "version_major": version_major,
            "version_minor": version_minor,
            "version_rev": version_patch,
        }

    def generate_version_file(self, directory: str) -> None:
        """
        Creates the version file as version.F90

        Args:
            directory (str): The directory to create the version file in

        Returns:
            None
        """
        import os

        version_functions = """
        integer pure function VERSION_NUMBER(Major, Minor, Rev) result(vn)
        implicit none
        integer, intent(in) :: major, minor, rev
        vn = ior(ior(ishft(major,20),ishft(minor,10)),rev)
        end function VERSION_NUMBER
        
        logical pure function CMP_VERSION_NUMBERS(a,b) result(match)
        implicit none
        integer, intent(in) ::  a, b
        match = ishft(a,-10) == ishft(b,-10)
        end function CMP_VERSION_NUMBERS"""

        file_name = os.path.join(directory, "version.F90")
        with open(file_name, "w") as f:
            version_length = len(self.__tag)
            hash_length = len(self.__hash)
            f.write("! This file is automatically generated by the ADCIRC versioning system\n")
            f.write("      module mod_adcirc_version\n")
            f.write(
                f'        character({version_length}), parameter :: AdcircVersionStr = "{self.__tag}"\n'
            )
            f.write(
                f'        character({hash_length}), parameter :: AdcircHashStr = "{self.__hash}"\n'
            )
            f.write(
                f"        integer, parameter :: AdcircVersionMajor = {self.__version_major}\n"
            )
            f.write(
                f"        integer, parameter :: AdcircVersionMinor = {self.__version_minor}\n"
            )
            f.write(
                f"        integer, parameter :: AdcircVersionRev = {self.__version_patch}\n"
            )
            f.write("      contains")
            f.writelines(version_functions)
            f.write("\n")
            f.write("      end module mod_adcirc_version\n")

    @staticmethod
    def __in_git_repo() -> bool:
        """
        Check if we are in a git repository or an exported tarball

        Returns:
            bool: True if we are in a git repository, False otherwise
        """
        import subprocess

        cmd = ["git", "status"]
        try:
            subprocess.check_output(cmd, stderr=subprocess.DEVNULL)
            return True
        except subprocess.CalledProcessError:
            return False

    @staticmethod
    def __get_git_hash() -> Tuple[str, str]:
        """
        Get the git commit hash

        Returns:
            Tuple[str, str]: The commit hash and tag
        """
        import subprocess

        cmd = ["git", "describe", "--always", "--tags"]
        git_tag = subprocess.check_output(cmd).strip().decode("utf-8")

        cmd = ["git", "rev-parse", "HEAD"]
        git_hash = subprocess.check_output(cmd).strip().decode("utf-8")

        return git_hash, git_tag

    @staticmethod
    def __parse_version_file(filename: str) -> Tuple[str, str, int, int, int]:
        """
        Parse the existing version file for the hash and tag

        Args:
            filename (str): The version file name
        """
        tag = "unknown"
        hash = "unknown"
        version_major = 0
        version_minor = 0
        version_patch = 0
        with open(filename, "r") as f:
            for line in f:
                if "AdcircVersionStr" in line:
                    tag = line.split("=")[1].strip().strip('"')
                elif "AdcircHashStr" in line:
                    hash = line.split("=")[1].strip().strip('"')
                elif "AdcircVersionMajor" in line:
                    version_major = int(line.split("=")[1].strip())
                elif "AdcircVersionMinor" in line:
                    version_minor = int(line.split("=")[1].strip())
                elif "AdcircVersionRev" in line:
                    version_patch = int(line.split("=")[1].strip())
        return hash, tag, version_major, version_minor, version_patch

    @staticmethod
    def __get_version_from_tag(tag: str) -> Tuple[int, int, int]:
        """
        Get the version from git describe. This assumes the git description is in the format
        vX.Y.Z or vX.Y.Z-git_rev-git_hash

        Args:
            tag (str): The tag to parse

        Returns:
            Tuple[int, int, int]: The major, minor and patch version
        """
        version = tag[1:].split("-")[0].split(".")
        if len(version) == 3:
            return int(version[0]), int(version[1]), int(version[2])
        elif len(version) == 2:
            return int(version[0]), int(version[1]), 0
        else:
            raise ValueError("Invalid version format")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Create the ADCIRC version file")
    parser.add_argument(
        "--create-version-file",
        help="Create the version file",
        action="store_true",
        default=False,
    )
    parser.add_argument(
        "--tag", help="Print the version to standard out", action="store_true"
    )
    parser.add_argument(
        "--hash", help="Print the tag to standard out", action="store_true"
    )
    parser.add_argument(
        "--directory",
        help="The directory to create the version file in",
        type=str,
        required=True,
    )

    args = parser.parse_args()

    if not args.directory and args.create_version_file:
        raise ValueError("Must provide a directory to create the version file in")

    versioning = AdcircVersion(args.directory)

    if args.create_version_file:
        versioning.generate_version_file(args.directory)

    if args.tag:
        print(versioning.tag())
    elif args.hash:
        print(versioning.hash())
