# ######################################################################################################################
#
# ADCIRC - The ADvanced CIRCulation model Copyright (C) 1994-2023 R.A. Luettich, Jr., J.J. Westerink
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# ######################################################################################################################

if(ADCIRC_SUN)
  set(ADCIRC_MACHINE_FLAG "CMACHSUN")
elseif(ADCIRC_SGI)
  set(ADCIRC_MACHINE_FLAG "SGI")
elseif(ADCIRC_CRAY)
  set(ADCIRC_MACHINE_FLAG "CRAY")
elseif(ADCIRC_CRAYX1)
  set(ADCIRC_MACHINE_FLAG "CRAYX1")
elseif(UNIX)
  set(ADCIRC_MACHINE_FLAG "LINUX")
elseif(CYGWIN)
  set(ADCIRC_MACHINE_FLAG "LINUX")
elseif(WIN32)
  set(ADCIRC_MACHINE_FLAG "WINDOWS")
elseif(APPLE)
  set(ADCIRC_MACHINE_FLAG "LINUX")
endif()

if(ADCIRC_SUN_MACHINE)
  set(ADCIRC_MACHINE_FLAG "${MACHINE_FLAG} -CMACHSUN")
endif()

if(ADCIRC_ENABLE_WARN_ELEV_DEBUG)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} DEBUG_WARN_ELEV")
endif()

if(ADCIRC_ENABLE_POWELL)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} POWELL")
endif()

if(ADCIRC_DEBUG_FULL_STACK)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} FULL_STACK")
endif()

if(ADCIRC_DEBUG_ALL_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} ALL_TRACE")
endif()

if(ADCIRC_DEBUG_FLUSH_MESSAGES)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} FLUSH_MESSAGES")
endif()

if(ADCIRC_DEBUG_LOG_LEVEL)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} EBUG")
endif()

if(ADCIRC_DEBUG_GLOBALIO_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} GLOBALIO_TRACE")
endif()

if(ADCIRC_DEBUG_WRITER_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} WRITER_TRACE")
endif()

if(ADCIRC_DEBUG_WRITE_OUTPUT_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} WRITE_OUTPUT_TRACE")
endif()

if(ADCIRC_DEBUG_WIND_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} WIND_TRACE")
endif()

if(ADCIRC_DEBUG_WEIR_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} WEIR_TRACE")
endif()

if(ADCIRC_DEBUG_TVW_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} TVW_TRACE")
endif()

if(ADCIRC_DEBUG_VSMY_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} VSMY_TRACE")
endif()

if(ADCIRC_DEBUG_TIMESTEP_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} TIMESTEP_TRACE")
endif()

if(ADCIRC_DEBUG_SUBPREP_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} SUBPREP_TRACE")
endif()

if(ADCIRC_DEBUG_SUBDOMAIN_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} SUBDOMAIN_TRACE")
endif()

if(ADCIRC_DEBUG_READ_INPUT_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} SUBDOMAIN_TRACE")
endif()

if(ADCIRC_DEBUG_OWIWIND_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} OWIWIND_TRACE")
endif()

if(ADCIRC_DEBUG_NODALATTR_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} NODALATTR_TRACE")
endif()

if(ADCIRC_DEBUG_NETCDF_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} NETCDF_TRACE")
endif()

if(ADCIRC_DEBUG_MESSENGER_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} MESSENGER_TRACE")
endif()

if(ADCIRC_DEBUG_MESH_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} MESH_TRACE")
endif()

if(ADCIRC_DEBUG_HOTSTART_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} HOTSTART_TRACE")
endif()

if(ADCIRC_DEBUG_GLOBAL_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} GLOBAL_TRACE")
endif()

if(ADCIRC_DEBUG_HARM_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} HARM_TRACE")
endif()

if(ADCIRC_DEBUG_COLDSTART_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} COLDSTART_TRACE")
endif()

if(ADCIRC_DEBUG_COUPLE2SWAN_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} COUPLE2SWAN_TRACE")
endif()

if(ADCIRC_DEBUG_ADCIRC_TRACE)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} ADCIRC_TRACE")
endif()

if(ADCIRC_DEBUG_HOLLAND)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} DEBUG_HOLLAND")
endif()

if(ADCIRC_DEBUG_NWS14)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} DEBUG_NWS14")
endif()

if(ADCIRC_IBM)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} IBM")
endif()

if(ADCIRC_VECTOR_COMPUTER)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} CVEC")
else()
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} CSCA")
endif()

if(ADCIRC_DATETIME)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} DATETIME")
endif()

if(ADCIRC_GRIB2)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} GRIB2API")
endif()

if(ADCIRC_NOF2008)
  set(ADCIRC_OPTION_FLAGS "${ADCIRC_OPTION_FLAGS} NOF2008")
endif(ADCIRC_NOF2008)

set(ADCIRC_SWAN_FLAG "CSWAN")
set(ADCIRC_PREP_SWAN_FLAG "ADCSWAN")
set(ADCIRC_MPI_FLAG "CMPI ${MPIMOD_FLAG}")
