
ADD_LIBRARY(version ${CMAKE_SOURCE_DIR}/version.F)
ADD_CUSTOM_COMMAND( OUTPUT ${CMAKE_SOURCE_DIR}/version.F
    COMMAND ./adcircVersion.sh ${CMAKE_SOURCE_DIR}
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/work/scripts
    COMMENT "Generating ADCIRC version...")
SET_TARGET_PROPERTIES(version PROPERTIES Fortran_MODULE_DIRECTORY CMakeFiles/version_mod)
SET_TARGET_PROPERTIES(version PROPERTIES COMPILE_FLAGS "${Fortran_LINELENGTH_FLAG} ${Fortran_COMPILER_SPECIFIC_FLAG}") 
