name: Build ADCIRC Workflow Template
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      DOCKERHUB_LOGIN_USERNAME:
        required: true
      DOCKERHUB_LOGIN_TOKEN:
        required: true

jobs:
  adcirc-container:
    name: Build ADCIRC container
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push ADCIRC Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./containers/Dockerfile
          push: true
          platforms: linux/amd64
          tags: adcircorg/adcirc:${{ inputs.tag }}
          labels: org.adcircorg.adcirc
