name: Pull Request ADCIRC Container Build

# Trigger the workflow every day at 5 AM (UTC).
on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    uses: ./.github/workflows/build_container.yaml
    with:
      tag: pr-${{ github.event.number }}
      push: false
    secrets: inherit
