name: Nightly ADCIRC Container Build

# Trigger the workflow every day at 5 AM (UTC).
on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  push-build:
    uses: ./.github/workflows/build_container.yaml
    with:
      tag: nightly 
    secrets: inherit
