name: Build and Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build:
    if: github.repository == 'adcirc/adcirc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
          # Add any other dependencies your documentation requires

      - name: Build documentation
        run: |
          cd docs
          make html
          # Create .nojekyll file to disable Jekyll processing
          touch _build/html/.nojekyll

      - name: Upload build artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: docs-html
          path: docs/_build/html/

  deploy:
    if: github.event_name == 'push' && github.repository == 'adcirc/adcirc'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: docs-html
          path: ./docs/_build/html/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          publish_branch: gh-pages
          force_orphan: true  # This creates a clean gh-pages branch
          commit_message: "[ci skip] docs: ${{ github.event.head_commit.message }}"